# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simplificator-ruby-kiva}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["simplificator"]
  s.date = %q{2010-04-12}
  s.description = %q{a ruby wrapper for the kiva.org api}
  s.email = %q{info@simplificator.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ruby-kiva/api.rb",
     "lib/ruby-kiva/borrower.rb",
     "lib/ruby-kiva/comment.rb",
     "lib/ruby-kiva/country.rb",
     "lib/ruby-kiva/dynamic_initializer.rb",
     "lib/ruby-kiva/image.rb",
     "lib/ruby-kiva/journal_entry.rb",
     "lib/ruby-kiva/lender.rb",
     "lib/ruby-kiva/lending_action.rb",
     "lib/ruby-kiva/loan.rb",
     "lib/ruby-kiva/location.rb",
     "lib/ruby-kiva/paged_array.rb",
     "lib/ruby-kiva/partner.rb",
     "lib/ruby-kiva/payment.rb",
     "lib/ruby-kiva/team.rb",
     "lib/ruby-kiva/terms.rb",
     "lib/ruby-kiva/video.rb",
     "lib/simplificator-ruby-kiva.rb",
     "simplificator-ruby-kiva.gemspec",
     "test/helper.rb",
     "test/test_simplificator-ruby-kiva.rb",
     "test/unit/borrower_test.rb",
     "test/unit/comment_test.rb",
     "test/unit/country_test.rb",
     "test/unit/image_test.rb",
     "test/unit/journal_entry_test.rb",
     "test/unit/lender_test.rb",
     "test/unit/payment_test.rb"
  ]
  s.homepage = %q{http://github.com/simplificator/simplificator-ruby-kiva}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{a ruby wrapper for the kiva.org api}
  s.test_files = [
    "test/helper.rb",
     "test/test_simplificator-ruby-kiva.rb",
     "test/unit/borrower_test.rb",
     "test/unit/comment_test.rb",
     "test/unit/country_test.rb",
     "test/unit/image_test.rb",
     "test/unit/journal_entry_test.rb",
     "test/unit/lender_test.rb",
     "test/unit/payment_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

